
import theZoo from "../assets/images/canvas/the zoo/1.jpg";
import hamsboHome from "../assets/images/canvas/hamsbo-home/10.jpg";
import hamsboEat from "../assets/images/canvas/hamsbo-eat/20.jpg";
import historyCourse from "../assets/images/canvas/history/29.jpg";
import poemCourse from "../assets/images/canvas/poem/38.jpg";

export const eventList = [
    {
      event_id: "123",
      title: "Khám phá sở thủ cùng HAMSBO",
      time_from: "21:00",
      time_to: "22:00",
      bonus_point_from: 50,
      bonus_point_to: 200,
      description: "Hành trình với sao Hỏa nha!",
      image_uri: theZoo,
      rewards: {},
      join_conditions: {},
      hashtags: ["happiness", "math", "science"],
      joined_members: 100,
      address: "Bình Dương",
    },
    {
      event_id: "34",
      title: "Khám phá ngôi nhà của HAMSBO",
      time_from: "21:00",
      time_to: "22:00",
      bonus_point_from: 50,
      bonus_point_to: 200,
      description: "Hành trình với sao Hỏa nha!",
      image_uri: hamsboHome,
      rewards: {},
      join_conditions: {},
      hashtags: ["happiness", "math", "science"],
      joined_members: 100,
      address: "Bình Dương",
    },
    {
      event_id: "546",
      title: "Ăn gì cùng HAMSBO",
      time_from: "21:00",
      time_to: "22:00",
      bonus_point_from: 50,
      bonus_point_to: 200,
      description: "Hành trình với sao Hỏa nha!",
      image_uri: hamsboEat,
      rewards: {},
      join_conditions: {},
      hashtags: ["happiness", "math", "science"],
      joined_members: 100,
      address: "Bình Dương",
    },
    {
      event_id: "547",
      title: "Lịch sử",
      time_from: "21:00",
      time_to: "22:00",
      bonus_point_from: 50,
      bonus_point_to: 200,
      description: "Hành trình với sao Hỏa nha!",
      image_uri: historyCourse,
      rewards: {},
      join_conditions: {},
      hashtags: ["happiness", "math", "science"],
      joined_members: 100,
      address: "Bình Dương",
    },
    {
      event_id: "548",
      title: "Bài thơ Nam Quốc sơn hà",
      time_from: "21:00",
      time_to: "22:00",
      bonus_point_from: 50,
      bonus_point_to: 200,
      description: "Hành trình với sao Hỏa nha!",
      image_uri: poemCourse,
      rewards: {},
      join_conditions: {},
      hashtags: ["happiness", "math", "science"],
      joined_members: 100,
      address: "Bình Dương",
    },
  ];